package com.github.sweettooth.model.api;

import com.github.sweettooth.model.locations.Location;

public interface ILocation {
	
	/**
	 * Returns the corresponding enum object for the specified official name of a location.
	 * @param name the official name of a location
	 * @return an enum object representing the specified name
	 * @exception IllegalArgumentException if the argument is not a valid location name
	 */
	static ILocation valueOfficialName(String name) throws IllegalArgumentException {
		return Location.valueOfficialName(name);
	}
	
	/**
	 * Uses the values() method automatically generated by the compiler in enums.
	 * @return an array containing all enum entries
	 */
	static ILocation[] values() {
		return Location.values();
	}
	
	/**
	 * Returns the official name of a location represented by this enum entry.
	 * @return 	the official name of this location
	 */
	String getOfficialName();
}
